GET http://localhost:3000
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFpc3lhaCIsInBhc3N3b3JkIjoiMTM1NzkiLCJuYW1lIjoiYWlzeWFoIiwiZW1haWwiOiJhaXN5YWgwMDAzMjZAZ21haWwuY29tIiwiaWF0IjoxNjgxMzY5ODc3LCJleHAiOjE2ODEzNjk5Mzd9.fRYovkCYDuIzp8z8aShbsYWki7eYrtRgCpckFDSJevQ

###

GET http://localhost:3000/bye
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFpc3lhaCIsInBhc3N3b3JkIjoiMTM1NzkiLCJuYW1lIjoiYWlzeWFoIiwiZW1haWwiOiJhaXN5YWgwMDAzMjZAZ21haWwuY29tIiwiaWF0IjoxNjgxMzY5ODc3LCJleHAiOjE2ODEzNjk5Mzd9.fRYovkCYDuIzp8z8aShbsYWki7eYrtRgCpckFDSJevQ

###


POST http://localhost:3000/login
Content-Type: application/json 
//header : what is the content type

{
    "username": "aisyah",
    "password": "13579"
}

###

POST http://localhost:3000/register
Content-Type: application/json 
//header : what is the content type

{
    "username": "aisyah",
    "password": "password",
    "name": "aisyah",
    "email": "asiayah"
}